# Generated by Django 5.2 on 2025-07-01 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_material_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='Np. 17cm, 18cm, S, M, L', max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Opcjonalnie. Nadpisuje cenę produktu bazowego. Zostaw puste, aby użyć ceny bazowej.', max_digits=6, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_sale', models.BooleanField(default=False)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Opcjonalnie. Cena wyprzedaży dla tej wariacji.', max_digits=6, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='store.product')),
            ],
            options={
                'unique_together': {('product', 'size')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='variation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.productvariation'),
            preserve_default=False,
        ),
    ]
