# Generated by Django 5.2 on 2025-07-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_order_product_alter_profile_date_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.CharField(blank=True, help_text='Np. 17cm, 18cm, S, M, L', max_length=50),
        ),
    ]
