# Generated by Django 5.2 on 2025-07-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_productvariation_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.CharField(blank=True, help_text='Np. 17cm, 18cm, S, M, L', max_length=50, null=True),
        ),
    ]
