# Generated by Django 5.2 on 2025-07-06 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_productvariation_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariation',
            options={'ordering': ['size']},
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='is_sale',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.productvariation'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.CharField(blank=True, default=1, help_text='Np. 17cm, 18cm, S, M, L', max_length=50),
            preserve_default=False,
        ),
    ]
