# Generated by Django 5.2 on 2025-07-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.CharField(default='#33f9ff', help_text='Kod heksadecymalny koloru, np. #FF5733', max_length=7),
        ),
    ]
