# Generated by Django 5.2 on 2025-07-21 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_material_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='color',
        ),
    ]
