# Generated by Django 5.2 on 2025-07-23 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_material_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zipcode',
        ),
    ]
