# Generated by Django 5.2 on 2025-07-27 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_profile_address1_remove_profile_address2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='variation',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
