# Generated by Django 5.2 on 2025-07-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_orderitem_variation_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='temp', editable=False, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
