# Generated by Django 5.2 on 2025-07-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='default_billing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='default_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
